Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
  config.vm.synced_folder ".", "/var/www/html"  
config.vm.provider "virtualbox" do |vb|
  vb.memory = "512"  
end
config.vm.provision "shell", inline: <<-SHELL
  # Packages vom lokalen Server holen
  # sudo sed -i -e"1i deb {{config.server}}/apt-mirror/mirror/archive.ubuntu.com/ubuntu xenial main restricted" /etc/apt/sources.list 
  sudo apt-get update
  sudo apt-get -y install apache2 
  sudo ufw deny 3306
  sudo ufw allow from 192.168.0.1 to any port 22
  sudo ufw allow from 192.168.0.1 to any port 3306
  sudo ufw enable
  sudo ufw status
  #Passwort
  sudo apt update
  sudo apt install apache2-utils
  vi /etc/apache2/sites-enabled/000-default.conf
  sudo nano /etc/apache2/sites-enabled/000-default.conf
  sudo nano .htaccess
  cat .htaccess
  sudo service apache2 restart
SHELL
end