Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
  config.vm.synced_folder ".", "/var/www/html"  
config.vm.provider "virtualbox" do |vb|
  vb.memory = "512"  
end
config.vm.provision "shell", inline: <<-SHELL
  sudo apt-get update
  sudo apt-get -y install apache2 
  sudo ufw deny 3306
  sudo ufw allow from 192.168.0.1 to any port 22
  sudo ufw allow from 192.168.0.1 to any port 3306
  sudo ufw enable
  sudo ufw status
  #Passwort
  sudo apt update
  sudo apt install apache2-utils
  rm -rf /etc/apache2/sites-enabled/000-default.conf 
  echo '<VirtualHost *:80>' >> /etc/apache2/sites-enabled/000-default.conf 
  echo 'ServerAdmin webmaster@localhost' >> /etc/apache2/sites-enabled/000-default.conf
  echo 'DocumentRoot /var/www/html' >> /etc/apache2/sites-enabled/000-default.conf
  echo 'ErrorLog ${APACHE_LOG_DIR}/error.log' >> /etc/apache2/sites-enabled/000-default.conf
  echo 'CustomLog ${APACHE_LOG_DIR}/access.log combined' >> /etc/apache2/sites-enabled/000-default.conf
  echo '<Directory "/var/www/html"' >> /etc/apache2/sites-enabled/000-default.conf
  echo 'AuthType Basic' >> /etc/apache2/sites-enabled/000-default.conf
  echo 'AuthName "Restricted Content"' >> /etc/apache2/sites-enabled/000-default.conf
  echo 'AuthUserFile /etc/apache2/.htpasswd' >> /etc/apache2/sites-enabled/000-default.conf
  echo 'Require valid-user' >> /etc/apache2/sites-enabled/000-default.conf
  echo '</Directory>'  >> /etc/apache2/sites-enabled/000-default.conf
  echo '</VirtualHost>' >> /etc/apache2/sites-enabled/000-default.conf
  rm -rf /etc/apache2/apache2.conf
  echo '<Directory /var/www/' >> /etc/apache2/apache2.conf
  echo Options Indexes FollowSymLinks >> /etc/apache2/apache2.conf
  echo AllowOverride All >> /etc/apache2/apache2.conf
  echo Require all granted >> /etc/apache2/apache2.conf
  echo '</Directory>' >> /etc/apache2/apache2.conf
  sudo service apache2 restart
SHELL
end